### PR TITLE
Added solution for Minimize the heights II(Python)

### PR DESCRIPTION
**Pull request by AkshayGidwani405**

### CODE REVIEW

**Comment by AkshayGidwani405** [comment]
Hi @anomekumar08! May I know the reason for marking my PR as invalid?

**Comment by anomekumar08** [comment]
> Hi @anomekumar08! May I know the reason for marking my PR as invalid?

You were not assigned for this issue. @AkshayGidwani405

**Comment by AkshayGidwani405** [comment]
@anomekumar08 If you check your contribution guidelines, you will no where find that a contributor needs to get assigned to a issue before making a PR. If so it should be explicitly mentioned.

**Comment by anomekumar08** [comment]
Ok..That's my fault..I am merging..

**Pull request merged**
