### PR TITLE
Added the file in C++.

### PR DESCRIPTION
**Pull request by MayankUghade**
Added the file in C++ language. Hope you find it interesting.

### CODE REVIEW

**Comment by anomekumar08** [comment]
Merge your commit or drop it and then create pull req with single commit.

**Comment by MayankUghade** [comment]
Ok sir 
I will do it till today evening

**Comment by anomekumar08** [comment]
It will be good if you add a readme file and explain your program.

**Comment by MayankUghade** [comment]
Sure thing 👍😊

**Pull request closed without merging**
