### PR TITLE
Final solution

### PR DESCRIPTION
**Pull request by mb-008**
This is the  solution of spiral traversal of matrix question

### CODE REVIEW

**Comment by mb-008** [comment]
@anomekumar08 can u tell me why u have added the invalid label in this and not accepted my pr?

**Comment by mb-008** [comment]
@anomekumar08  i am a neewbee in the field of open-source and i realized my mistake in this code now.From now on i will take care of these things but please for now can u remove the invalid label from it please because due to this my chances of getting disqualified in the hacktoberfest are increasing.  I would be forever greatful to you.

**Comment by mb-008** [comment]
i will  remove my pr once you will do that.

**Comment by anomekumar08** [comment]
Make any quality project or program of your own and then open pr... I will surely merge it @mb-008

**Pull request closed without merging**
